### ISSUE TITLE
Include minified version (angular-bind-html-compile.min.js) into bower component

### ISSUE THREAD

**Issue by ivanfilhoz** [incuna/angular-bind-html-compile#16]
Like most components usually do, it would be nice to have an up-to-date minified version bundled into angular-bind-html-compile.

**Comment by wytrych** [comment]
Hi, thanks for your input. Please feel free to submit a PR.

**Comment by ivanfilhoz** [comment]
Just did it, please accept PR #17

**Comment by zuzusik** [comment]
I guess, this can be closed, right?

**Comment by ivanfilhoz** [comment]
Yes, it's done already.

Em sex, 25 de mar de 2016 12:07, Viktor Zozuliak notifications@github.com
escreveu:

**Comment by wytrych** [comment]
Done in #17
