### ISSUE TITLE
bower requirement for angular 1.2

### ISSUE THREAD

**Issue by eroux** [incuna/angular-bind-html-compile#9]
I tried to install your package through bower on a platform with a recent angular, it was impossible due to the requirement of angular ~1.2 in this project's bower.json. Why such an outdated requirement?

**Comment by eroux** [comment]
(P.S.: bower is supple enough to allow this, but the message is quite disturbing...)

**Comment by zuzusik** [comment]
It would be really great if this change is released to bower and npm.
Under `1.2.1` for example. What do you think?

**Comment by wytrych** [comment]
@zuzusik released as `1.2.1`
